paths:
  root:  '/orcd/pool/008/yjouwang/9_Tall3D/7_bot_de'

ls:
  field_name: 'Integral length scale'
  save_to:  '/orcd/pool/008/yjouwang/9_Tall3D/7_bot_de/ls'

grids:

  grid_2:
    name: '2h'
    dir: '/orcd/pool/008/yjouwang/9_Tall3D/7_bot_de/2h'
    N: 2094751
    V: 0.01398  
    field_file_name: 'ils.csv'

  grid_4:
    name: '4h'
    dir: '/orcd/pool/008/yjouwang/9_Tall3D/7_bot_de/4h'
    N: 456351
    V: 0.01398  
    field_file_name: 'ils.csv'

  grid_6:
    name: '6h'
    dir: '/orcd/pool/008/yjouwang/9_Tall3D/7_bot_de/6h'
    N: 163257
    V: 0.01398  
    field_file_name: 'ils.csv'

  grid_8:
    name: '8h'
    dir: '/orcd/pool/008/yjouwang/9_Tall3D/7_bot_de/8h'
    N: 237738
    V: 0.01398  
    field_file_name: 'ils.csv'

points: 
  start: 0
  end: 1809
